<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Central European Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 7" host="VDI-UBS-06"><DocLocation><![CDATA[P:\Users\ANetsman\Documents\Unified Functional Testing\OutlookTest]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[OutlookTest]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[SheduleAnAppointment]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Calendar ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:01]]></Time>
<TimeTick>1479456481</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Calendar ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Календар - ANetsman@luxoft.com]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:02]]></Time>
<TimeTick>1479456482</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[New Appointment.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:02]]></Time>
<TimeTick>1479456482</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" >
<Disp><![CDATA[New Appointment.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Календар - ANetsman@luxoft.com]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Untitled - Appointment]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Subject:.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["qwerty"]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" >
<Disp><![CDATA[Subject:.SetValue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" >
<Disp><![CDATA[Untitled - Appointment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Setting Subject]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<NodeArgs eType="User" icon="8" nRep="16" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Untitled - Appointment]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Location:]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAComboBox]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Location:.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["qwerty"]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:03]]></Time>
<TimeTick>1479456483</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[Location:.SetValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Location:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["qwerty"]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:04]]></Time>
<TimeTick>1479456484</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" >
<Disp><![CDATA[Location:.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="19" >
<Disp><![CDATA[Location:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" >
<Disp><![CDATA[Untitled - Appointment]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Setting Location]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:04]]></Time>
<TimeTick>1479456484</TimeTick>
<NodeArgs eType="User" icon="8" nRep="23" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Recurrence... ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:06]]></Time>
<TimeTick>1479456486</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" >
<Disp><![CDATA[[ Recurrence... ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Daily  ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:07]]></Time>
<TimeTick>1479456487</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="27" >
<Disp><![CDATA[[ Daily  ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:08]]></Time>
<TimeTick>1479456488</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Setting Occurence]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:08]]></Time>
<TimeTick>1479456488</TimeTick>
<NodeArgs eType="User" icon="8" nRep="30" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Invite Attendees ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:08]]></Time>
<TimeTick>1479456488</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" >
<Disp><![CDATA[[ Invite Attendees ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Untitled - Meeting Series]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:09]]></Time>
<TimeTick>1479456489</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[To.SetValue]]></Obj>
<Details plainTxt="False" ><![CDATA["Netsman, Oleksandr &ltANetsman@luxoft.com&gt"]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:09]]></Time>
<TimeTick>1479456489</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" >
<Disp><![CDATA[To.SetValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[To.Type]]></Obj>
<Details plainTxt="False" ><![CDATA[" "]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:09]]></Time>
<TimeTick>1479456489</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" >
<Disp><![CDATA[To.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" >
<Disp><![CDATA[Untitled - Meeting Series]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Adding Attenders]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:09]]></Time>
<TimeTick>1479456489</TimeTick>
<NodeArgs eType="User" icon="8" nRep="38" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Send ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:10]]></Time>
<TimeTick>1479456490</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" >
<Disp><![CDATA[[ Send ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Untitled - Meeting Series]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:11]]></Time>
<TimeTick>1479456491</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Microsoft Outlook]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:11]]></Time>
<TimeTick>1479456491</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Send Anyway.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:11]]></Time>
<TimeTick>1479456491</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" >
<Disp><![CDATA[Send Anyway.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="43" >
<Disp><![CDATA[Microsoft Outlook]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="42" >
<Disp><![CDATA[Untitled - Meeting Series]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Setting A New Appointment]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:11]]></Time>
<TimeTick>1479456491</TimeTick>
<NodeArgs eType="User" icon="8" nRep="45" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Pass]]></Obj>
<Details ><![CDATA[Shedule an appointment]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:11]]></Time>
<TimeTick>1479456491</TimeTick>
<NodeArgs eType="User" icon="8" nRep="46" status="Passed" Source="SheduleAnAppointment" SourceLine="25" >
<Disp><![CDATA[Pass]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/18/2016 - 9:07:55" eTime="11/18/2016 - 9:08:13" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[SheduleAnAppointment Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[SwitchBetweenTabs]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Вхідні - ANetsman@luxoft.com]]></Obj>
<Details plainTxt="False" ><![CDATA[UIAWindow]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:16]]></Time>
<TimeTick>1479456496</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Ribbon Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[UIATab]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:16]]></Time>
<TimeTick>1479456496</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[View.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:16]]></Time>
<TimeTick>1479456496</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="52" >
<Disp><![CDATA[View.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:18]]></Time>
<TimeTick>1479456498</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="54" >
<Disp><![CDATA[Home.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Folder.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:19]]></Time>
<TimeTick>1479456499</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="56" >
<Disp><![CDATA[Folder.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="51" >
<Disp><![CDATA[Ribbon Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" >
<Disp><![CDATA[Вхідні - ANetsman@luxoft.com]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/18/2016 - 9:08:13" eTime="11/18/2016 - 9:08:21" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="48" >
<Disp><![CDATA[SwitchBetweenTabs Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T37">
<AName><![CDATA[SwitchBetweenApps]]></AName>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ Calendar ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:27]]></Time>
<TimeTick>1479456507</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="60" >
<Disp><![CDATA[[ Calendar ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Tasks ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:30]]></Time>
<TimeTick>1479456510</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="62" >
<Disp><![CDATA[[ Tasks ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ New E-mail ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[11/18/2016 - 9:08:32]]></Time>
<TimeTick>1479456512</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="64" >
<Disp><![CDATA[[ New E-mail ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="11/18/2016 - 9:08:21" eTime="11/18/2016 - 9:08:33" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="58" >
<Disp><![CDATA[SwitchBetweenApps Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T41">
<AName><![CDATA[GetOutlookParameters]]></AName>
<Summary sTime="11/18/2016 - 9:08:33" eTime="11/18/2016 - 9:08:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="66" >
<Disp><![CDATA[GetOutlookParameters Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[OutlookTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="11/18/2016 - 9:07:47" eTime="11/18/2016 - 9:08:48" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test OutlookTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>